config/routes.rb
Matchpuppy::Application.routes.draw do
  
  

  
  match 'privacy' => 'pages#privacy'
  match 'terms' => 'pages#terms'
  match 'contact' => 'pages#contact'
  match 'faq' => 'pages#faq'
  
  
  get "pages/terms"

  resources :park_loves
  resources :comments
  

 match 'account' => 'users#profile'
 match 'account/edit' => 'users#edit'
 
  
  resources :user_sessions
  
   resources :password_resets

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  resources :playdates do
    resources :playdate_guests
    resources :comments
  end
  
  match 'playdates/:id/join' => 'playdates#join'
  match 'playdates/:id/rsvp/:rsvp' => 'playdates#rsvp'
  
  
  
  
  resources :parks
  
  resources :posts

 root :to => 'users#new'
 

  
  resources :users do
    resources :dogs
  end
  
  
  resources :contact_us 
  
  match 'contact_us/send_email' => 'contact_us#send_email', :as => :send_email
   
  
  match 'dogs' => 'dogs#index'
  
  match 'admin/:action' => 'admin'
  
end

app/models/city_park.rb
class CityPark < ActiveResource::Base
  self.site = "http://www.nycgovparks.org/bigapps/DPR_DogRuns_001.xml"
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :playdate
  has_one :park, :through => :playdate
  
  after_save :notify
  
  
  private
  
  def notify
    PlaydateMailer.new_comment(self).deliver
  end
  
  
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Validations
  include ActiveModel::Conversion
  
  attr_accessor :name, :email, :body
  validates_presence_of :name, :email, :body
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end 
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :large=> "600",:medium => "300", :thumb => "150" }, :storage => :s3,
      :bucket => 'MatchPuppy',
      :s3_credentials => {
        :access_key_id => 'AKIAJYTNN7664YXLY5KA',
        :secret_access_key => '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'
      }, 
      :default_url => '/assets/default_dog_:style.png'
      
  validates_attachment_size :avatar, :less_than => 5.megabytes
  
  belongs_to :user
  has_many :playdate_guests, :dependent => :destroy
  has_one :park, :through => :user
  has_many :playdates, :through => :playdate_guests
  has_many :park_loves, :through => :user
  
  validates :name, :size, :breed, :gender, :energy, :age, :favorite, :presence => true
  
  self.per_page = 30
  
  
  
end

app/models/love.rb
class Love < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base
  
  has_many :playdates
  has_many :playdate_guests, :through => :playdates
  has_many :park_loves, :dependent => :destroy
  has_many :users, :through => :park_loves
  has_many :dogs, :through => :users
  
  
  
  def current_love
    if UserSession.find
      @park_love = ParkLove.where(:park_id => self.id, :user_id => UserSession.find.user.id)
      if @park_love.any?
        return true
      else
        return false
      end
    else 
      return false
    end
    
  end
  
end

app/models/park_love.rb
class ParkLove < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
  has_many :playdate_guests, :dependent => :destroy
  has_many :dogs, :through => :playdate_guests
  has_many :comments
  has_many :users, :through => :dogs
  
  validates :park_id, :description, :presence => true
  
  after_save :invite_guests
  
  scope :upcoming, where("playdates.play_date > ?", Time.now).order("play_date ASC")
  
  private 
  
  def invite_guests
    if self.status == "sent"
      self.users.each do |user| 
        if user != self.user
          PlaydateMailer.invite(self, user).deliver
        end
      end
      PlaydateMailer.create(self).deliver
    end
    
  end
  
  
  
end

app/models/playdate_guest.rb
class PlaydateGuest < ActiveRecord::Base
  belongs_to :playdate
  belongs_to :dog
  has_one :user, :through => :dog
  has_one :park, :through => :playdate
  
  scope :yes, where(:rsvp => 'Yes')
  scope :no, where(:rsvp => 'No')
  scope :maybe, where(:rsvp => 'Maybe')
  

 
end

app/models/user.rb
class User < ActiveRecord::Base
 
  acts_as_authentic do |c|
      c.merge_validates_format_of_email_field_options :message => 'not valid'
  end
  
  
  has_many :dogs, :dependent => :destroy
  has_many :playdates
  has_many :park_loves
  has_many :comments
  has_many :parks, :through => :park_loves
  
  validates :name, :email, :password, :presence => true

  
  
  after_create :signup_email
  
  
  def deliver_password_reset_instructions!  
    reset_perishable_token!  
    UserMailer.password_reset(self).deliver
  end
  
  private
  
  def signup_email
    UserMailer.signup(self).deliver
  end
  
  
  def mailing_list
    h = Hominid::API.new('eef9cbf1cbad4b743302e591e036190d-us4')
    h.list_subscribe(22865, 'joe@public.com', {'FNAME' => 'Joe', 'LNAME' => 'Public'}, 'html', false, true, true, false)
    
  end
  
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/playdate_guests_controller.rb
class PlaydateGuestsController < ApplicationController
  # GET /playdate_guests
  # GET /playdate_guests.json
  def index
    @playdate_guests = PlaydateGuest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @playdate_guests }
    end
  end

  # GET /playdate_guests/1
  # GET /playdate_guests/1.json
  def show
    @playdate_guest = PlaydateGuest.find(params[:id])
    @playdate = @playdate_guest.playdate
    
    if @playdate_guest.user == current_user
      redirect_to edit_playdate_playdate_guest_path(@playdate, @playdate_guest)
    else 
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @playdate_guest }
      end
    end
    
    
    
  end

  # GET /playdate_guests/new
  # GET /playdate_guests/new.json
  def new
    @playdate_guest = PlaydateGuest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @playdate_guest }
    end
  end

  # GET /playdate_guests/1/edit
  def edit
    @playdate_guest = PlaydateGuest.find(params[:id])
    @playdate = Playdate.find(params[:playdate_id])
  end

  # POST /playdate_guests
  # POST /playdate_guests.json
  def create
    @playdate_guest = PlaydateGuest.new(params[:playdate_guest])
    
    @playdate = Playdate.find(params[:playdate_id])
    @playdate_guest = @playdate.playdate_guests.new(params[:playdate_guest])
    @playdate_guest.rsvp = "Maybe"
    
    respond_to do |format|
      if @playdate_guest.save
        format.html { redirect_to @playdate, :notice => 'Playdate guest was successfully created.' }
        format.json { render :json => @playdate_guest, :status => :created, :location => @playdate_guest }
        format.js
      else
        format.html { redirect_to @playdate, :notice => 'ERROR - Playdate guest was not invited .' }
        format.json { render :json => @playdate_guest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /playdate_guests/1
  # PUT /playdate_guests/1.json
  def update
    @playdate_guest = PlaydateGuest.find(params[:id])
    @playdate = Playdate.find(params[:playdate_id])
    
    respond_to do |format|
      if @playdate_guest.update_attributes(params[:playdate_guest])
        format.html { redirect_to @playdate, :notice => 'Playdate guest was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @playdate_guest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playdate_guests/1
  # DELETE /playdate_guests/1.json
  def destroy
    @playdate_guest = PlaydateGuest.find(params[:id])
    @playdate_guest.destroy

    respond_to do |format|
      format.html { redirect_to playdate_guests_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/park_love_helper.rb
module ParkLoveHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/playdate_guests_helper.rb
module PlaydateGuestsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/playdate_guests/_form.html.erb
	
<div class="thumb">


<%= form_for([@playdate, @playdate_guest]) do |f| %>


 <h5><%= @playdate_guest.dog.name %></h5>

   <div class="clearfix">
    <%= f.label "RSVP?" %>
  	<div class="input">
		<%= f.select(:rsvp, options_for_select([['Yes'], ['Maybe'], ['No']])) %>
	</div>
  </div>

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/playdate_guests/_playdate_guest.erb
<li class="span2" class="thumbnail">

	
	<a href="<%= user_dog_path(playdate_guest.dog.user, playdate_guest.dog) %>" rel="popover" data-original-title="<%= playdate_guest.dog.name %>" data-content="
		<ul>
	    <li><b>Size:</b> <%= playdate_guest.dog.size %></li>
		<li><b>Breed:</b> <%= playdate_guest.dog.breed %></li>
		<li><b>Gender:</b> <%= playdate_guest.dog.gender %></li>
	  </ul>
		" data-html="true">
	<%= image_tag playdate_guest.dog.avatar.url(:thumb) %>
	
	</a>
	
	<h4><%= link_to playdate_guest.dog.name, playdate_playdate_guest_path(@playdate, playdate_guest) %></h4>
	<p>
		<% if playdate_guest.rsvp == "Yes" %>
			<i class="icon-ok"></i> Yes
	   	<% elsif playdate_guest.rsvp == "No"  %>
			<i class="icon-remove"></i> No
	    <% end %>
		
		
	</p>

</li>

app/views/playdate_guests/create.js.erb
$('ul#invited').append("<%= escape_javascript(render @playdate_guest) %>");
//$('div#<%= dom_id(@playdate_guest) %>').effect("highlight");

$('li#invitee<%= @playdate_guest.dog.id %>').hide();

app/views/playdate_guests/edit.html.erb
<h1>Editing playdate_guest</h1>

<%= render 'form' %>

app/views/playdate_guests/index.html.erb
<h1>Listing playdate_guests</h1>

<table>
  <tr>
    <th>Playdate</th>
    <th>Dog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playdate_guests.each do |playdate_guest| %>
  <tr>
    <td><%= playdate_guest.playdate_id %></td>
    <td><%= playdate_guest.dog_id %></td>
    <td><%= link_to 'Show', playdate_guest %></td>
    <td><%= link_to 'Edit', edit_playdate_guest_path(playdate_guest) %></td>
    <td><%= link_to 'Destroy', playdate_guest, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playdate guest', new_playdate_guest_path %>

app/views/playdate_guests/new.html.erb
<div class="page-header">
<h1>New playdate_guest</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', playdate_guests_path %>

app/views/playdate_guests/show.html.erb
<p id="notice"><%= notice %></p>





<h2>
  <b>Play date:</b>
  <%= l @playdate_guest.playdate.play_date, :format => :short %>
</h2>

<h3>
  
  <%= @playdate_guest.dog.name %>
</h3>

<p>
  <b>Park:</b>
  <%= @playdate_guest.playdate.park.name %>
</p>

<p>
  <b>Organizer:</b>
  <%= @playdate_guest.playdate.user.name %>
</p>

<p>
	<b>Owner</b>
	<%= @playdate_guest.user.name %>
</p>
<p>
  <b>RSVP:</b>
  <%= @playdate_guest.rsvp %>
</p>

<%= link_to "Back to Playdate", @playdate %>