config/routes.rb
Matchpuppy::Application.routes.draw do
  
  

  
  match 'privacy' => 'pages#privacy'
  match 'terms' => 'pages#terms'
  match 'contact' => 'pages#contact'
  match 'faq' => 'pages#faq'
  
  
  get "pages/terms"

  resources :park_loves
  resources :comments
  

 match 'account' => 'users#profile'
 match 'account/edit' => 'users#edit'
 
  
  resources :user_sessions
  
   resources :password_resets

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  resources :playdates do
    resources :playdate_guests
    resources :comments
  end
  
  match 'playdates/:id/join' => 'playdates#join'
  match 'playdates/:id/rsvp/:rsvp' => 'playdates#rsvp'
  
  
  
  
  resources :parks
  
  resources :posts

 root :to => 'users#new'
 

  
  resources :users do
    resources :dogs
  end
  
  
  resources :contact_us 
  
  match 'contact_us/send_email' => 'contact_us#send_email', :as => :send_email
   
  
  match 'dogs' => 'dogs#index'
  
  match 'admin/:action' => 'admin'
  
end

app/models/city_park.rb
class CityPark < ActiveResource::Base
  self.site = "http://www.nycgovparks.org/bigapps/DPR_DogRuns_001.xml"
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :playdate
  has_one :park, :through => :playdate
  
  after_save :notify
  
  
  private
  
  def notify
    PlaydateMailer.new_comment(self).deliver
  end
  
  
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Validations
  include ActiveModel::Conversion
  
  attr_accessor :name, :email, :body
  validates_presence_of :name, :email, :body
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end 
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :large=> "600",:medium => "300", :thumb => "150" }, :storage => :s3,
      :bucket => 'MatchPuppy',
      :s3_credentials => {
        :access_key_id => 'AKIAJYTNN7664YXLY5KA',
        :secret_access_key => '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'
      }, 
      :default_url => '/assets/default_dog_:style.png'
      
  validates_attachment_size :avatar, :less_than => 5.megabytes
  
  belongs_to :user
  has_many :playdate_guests, :dependent => :destroy
  has_one :park, :through => :user
  has_many :playdates, :through => :playdate_guests
  has_many :park_loves, :through => :user
  
  validates :name, :size, :breed, :gender, :energy, :age, :favorite, :presence => true
  
  self.per_page = 30
  
  
  
end

app/models/love.rb
class Love < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base
  
  has_many :playdates
  has_many :playdate_guests, :through => :playdates
  has_many :park_loves, :dependent => :destroy
  has_many :users, :through => :park_loves
  has_many :dogs, :through => :users
  
  
  
  def current_love
    if UserSession.find
      @park_love = ParkLove.where(:park_id => self.id, :user_id => UserSession.find.user.id)
      if @park_love.any?
        return true
      else
        return false
      end
    else 
      return false
    end
    
  end
  
end

app/models/park_love.rb
class ParkLove < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
  has_many :playdate_guests, :dependent => :destroy
  has_many :dogs, :through => :playdate_guests
  has_many :comments
  has_many :users, :through => :dogs
  
  validates :park_id, :description, :presence => true
  
  after_save :invite_guests
  
  scope :upcoming, where("playdates.play_date > ?", Time.now).order("play_date ASC")
  
  private 
  
  def invite_guests
    if self.status == "sent"
      self.users.each do |user| 
        if user != self.user
          PlaydateMailer.invite(self, user).deliver
        end
      end
      PlaydateMailer.create(self).deliver
    end
    
  end
  
  
  
end

app/models/playdate_guest.rb
class PlaydateGuest < ActiveRecord::Base
  belongs_to :playdate
  belongs_to :dog
  has_one :user, :through => :dog
  has_one :park, :through => :playdate
  
  scope :yes, where(:rsvp => 'Yes')
  scope :no, where(:rsvp => 'No')
  scope :maybe, where(:rsvp => 'Maybe')
  

 
end

app/models/user.rb
class User < ActiveRecord::Base
 
  acts_as_authentic do |c|
      c.merge_validates_format_of_email_field_options :message => 'not valid'
  end
  
  
  has_many :dogs, :dependent => :destroy
  has_many :playdates
  has_many :park_loves
  has_many :comments
  has_many :parks, :through => :park_loves
  
  validates :name, :email, :password, :presence => true

  
  
  after_create :signup_email
  
  
  def deliver_password_reset_instructions!  
    reset_perishable_token!  
    UserMailer.password_reset(self).deliver
  end
  
  private
  
  def signup_email
    UserMailer.signup(self).deliver
  end
  
  
  def mailing_list
    h = Hominid::API.new('eef9cbf1cbad4b743302e591e036190d-us4')
    h.list_subscribe(22865, 'joe@public.com', {'FNAME' => 'Joe', 'LNAME' => 'Public'}, 'html', false, true, true, false)
    
  end
  
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  
  before_filter :get_user, :except => :index
  before_filter :set_controller
  
  
  # GET /dogs
  # GET /dogs.json
  def index
    @title = "Dogs"
    @dogs = Dog.paginate :page => params[:page], :order => 'created_at DESC'
    
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])
    @user = @dog.user
    @title = @dog.name
    @playdates = Playdate.joins(:dogs).where("dogs.id" => @dog.id).where("play_date > ?", Time.now)
    @other_dogs = Dog.where("breed = ? and dogs.id <> ?", @dog.breed,@dog.id).limit(3).order("random()")
  
  end

  # GET /dogs/new
  # GET /dogs/new.json
  def new
    @dog = Dog.new
    @dog.name = flash[:dog_name]
    @dog.user_id = current_user.id

  end

  # GET /dogs/1/edit
  def edit
    @user = User.find(params[:user_id])
    @dog = Dog.find(params[:id])
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @user = User.find(params[:user_id])
    @dog = @user.dogs.new(params[:dog])
    
    if @dog.save
      if @user.dogs.count == 1
        redirect_to parks_path
      else
        redirect_to account_path
      end
    else
      render :action => "new"
    end
  end

  # PUT /dogs/1
  # PUT /dogs/1.json
  def update
    @user = User.find(params[:user_id])
    @dog = Dog.find(params[:id])

    if @dog.update_attributes(params[:dog])
    
          redirect_to account_path, :notice => 'Dog was successfully updated.'
      
    else
      render :action => "edit" 
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog = Dog.find(params[:id])
    
    if current_user.user_type == "admin" or current_user = @dog.user
      @dog.destroy
      redirect_to account_path 
    else 
      redirect_to root_path, :notice => "Not allowed to delete someone elses dog!"
    end
     
  end
  
 
 
  private
  
  def get_user
    @user = User.find(params[:user_id])
  end
  
  def set_controller
    @controller = 'dogs'
  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/park_love_helper.rb
module ParkLoveHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/_dog.html.erb
<li class="span2" style="margin-right:10px;">
<div class="thumbnail">





<a href="<%= user_dog_path(dog.user, dog) %>" rel="popover" data-placement="right" data-delayHide="5000" data-original-title="<%= dog.name %>" data-content="
	<ul class='unstyled''>
    <li><b>Size:</b> <%= dog.size %></li>
	<li><b>Breed:</b> <%= dog.breed %></li>
	<li><b>Gender:</b> <%= dog.gender %></li>
	<li><b>Age:</b> <%= dog.age %></li>
	<li><b>Energy:</b> <%= dog.energy %></li>
	<li><b>Owner:</b> <%= dog.user.name %></li>
	
	
	<li>&ldquo;<%= dog.favorite %>&rdquo;</li>
  </ul>
	" data-html="true">
	
	<% if dog.avatar_file_name == nil && dog.gender == "Female" %>
		<%= image_tag "/assets/default_dog_medium_female.png" %>
	<% else %>
		<%= image_tag dog.avatar.url(:medium) %>
	<% end %>	
	
	<h3><%= dog.name %></h3>
		
</a>


</div>
</li>

app/views/dogs/_form.html.erb
<%= form_for([@user, @dog], :html => { :class=>"form-horizontal"}) do |f| %>

<% if @dog.errors.any? %>
   <div class="alert alert-error">
     <strong>Whoops!</strong>

     <ul class="unstyled">
     <% @dog.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

<div class="well">
<div class="control-group">
	<%= f.label "Your dog's name" %>
	<div class="controls">

	<%= f.text_field(:name) %>
	</div>
</div>

<div class="control-group">
	<label>How big?</label>
	<div class="controls <% if @dog.errors[:size] != nil %>error<% end %>">
		<div class="row"  >
			<div class="span2" style >
				<label for="smalldog">
					<img src="/images/small.png"  id="smalldog-image"><br/>
					<%= f.radio_button( :size, "small", :id => "smalldog") %> Small (0-20lbs)
				</label>

			</div>
			<div class="span3" >
				<label for="mediumdog">
					<img src="/images/medium.png" id="mediumdog-image"><br/>
					<%= f.radio_button( :size, "medium", :id => "mediumdog") %> Medium (21-50lbs)
				</label>

			</div>
			<div class="span4" >
				<label for="largedog">
					<img src="/images/large.png" id="largedog-image"><br/>
					<%= f.radio_button( :size, "large", :id=>"largedog") %> Large (51lbs+)
				</label>

			</div>	
		</div>
	</div>
</div>

<div class="control-group ">
	<%= f.label "What breed?" %>
	<div class="controls">
		<%= f.select(:breed, options_for_select([
			['Beagle', 'Beagle'],
			['Boxer', 'Boxer'],
			['Bulldog'],
			['Chihuahua'],
			['Cocker Spaniel'],
			['Collie'],
			['Dachshund'],
			['German Shepherd'],
			['Golden Retriever'],
			['Great Dane'],
			['Labrador Retriever'],
			['Maltese'],
			['Miniature Schnauzer'],
			['Pinscher'],
			['Pitt Bull'],
			['Pomeranian'],
			['Poodle'],
			['Pug'],
			['Rottweiler'],
			['Saint Bernard'],
			['Siberian Husky'],
			['Shiba Inu'],
			['Shih Tzu'],
			['Yorkshire Terrier'],
			['Mixed'],
			['Other']
			], @dog.breed)) %>
	</div>
</div>

<div class="control-group">
	<%= f.label :gender %>
	<div class="controls">
		<div class = "row">
			<div class = "span2">
				<label for = "male">
					<%= image_tag 'male-paw.png' %> 
					<%= f.radio_button( :gender, "Male", :id => "male") %>
					Male
				</label>
			</div>
			<div class = "span2">
				<label for = "female">
					<%= image_tag 'female-paw.png' %> 
					<%= f.radio_button( :gender, "Female", :id => "female") %>
					Female
				</label>
			</div>
		</div>
	</div>
</div>

<div class="control-group ">
	<%= f.label "How old?" %>
	<div class="controls">
		<%= f.select(:age, options_for_select([
			['0-12 months'],
			['1-2 years'],
			['3-5 years'],
			['6-9 years'],
			['10+ years']
			], @dog.age)) %>
	</div>
</div>


<div class="control-group">
<%= f.label :energy, "Energy Level?"%>
	<div class="controls">
		<div class = "row">
			<div class = "span2">
				<label for = "Low">
					<%= f.radio_button( :energy, "Couch potato", :id => "Low") %>
					Couch potato
				</label>
			</div>
			<div class = "span2">
				<label for = "Medium">
					<%= f.radio_button( :energy, "Happy-go-lucky", :id => "Medium") %>
					Happy-go-lucky
				</label>
			</div>
			<div class = "span2">
				<label for = "High">
					<%= f.radio_button( :energy, "Life of the party", :id => "High") %>
					Life of the party
				</label>
			</div>
		</div>
	</div>
</div>


<!-- <div class="control-group">
<%= f.label "Modivation Type?"%>
<div class="controls">
	<div class = "row">
		<div class = "span3">
			<label for = "Low">

				<%= f.radio_button( :energy, "Internally", :id => "male") %>
				Internally motivated <a href="#"  rel="popover" data-content="Socially Modivated Dogs blah blah blah" data-original-title="Internally motivated">?</a>
			</label>
		</div>
		<div class = "span3">
			<label for = "Medium">

				<%= f.radio_button( :energy, "Externally", :id => "female") %>
				Externally motivated <a href="#"  rel="popover" data-content="Socially Modivated Dogs blah blah blah" data-original-title="Externally motivated">?</a>
			</label>
		</div>
		<div class = "span3">
			<label for = "High">

				<%= f.radio_button( :energy, "Socially", :id => "female") %>
				Socially motivated <a href="#"  rel="popover" data-content="Socially Modivated Dogs blah blah blah" data-original-title="Socially motivated">?</a>
			</label>
		</div>
	</div>
</div> -->



<div class="control-group">
	<%= f.label :Photo %>
	<div class="controls">
	<%= f.file_field :avatar %>
	</div>
</div>
<div class="control-group">
	<%= f.label "What do you love most about your dog?" %>
	<div class="controls">
		<%= f.text_area :favorite, :style=>"height:50px" %>
	</div>
</div>
</div>
<div class="form-actions">
	<%= f.submit nil, :class=>"btn btn-primary" %>
</div>
<% end %>

app/views/dogs/edit.html.erb
<% if notice %>
<div class="alert alert-success">
<%= notice %>
</div>
<% end %>


<div class="page-header">
<h1>Tell us about your dog
</h1>
</div>


<%= render 'form' %>

app/views/dogs/index.html.erb
<% content_for :title, "Title for specific page" %>


<div class="page-header">
<h1>Dogs who love Matchpuppy</h1>
</div>


<div class="row">



<div class="span12">
	
	<div class="well">
	
	
<ul class="thumbnails" id="dogs-container" style="margin-left:25px;">
<%= render @dogs %>
</ul>

<%= will_paginate @dogs %>
</div>

</div>
</div>

app/views/dogs/new.html.erb
<div class="page-header">
<h1>Tell us about your dog</h1>
</div>

<%= render 'form' %>

app/views/dogs/show.html.erb
<% content_for :head do %>
  	<meta property="og:image" content="<%= @dog.avatar.url(:thumb) %>"/>
	<meta property="og:url" content="<%= user_dog_url(@dog.user, @dog) %>"/>
	<link rel="canonical" href="<%= user_dog_url(@dog.user, @dog) %>" />
<% end %>


<% if notice %>
<div class      = "alert alert-success">
<%= notice %>
</div>
<% end %>

<div class      = "page-header">
	<div class     = "row">
		<div class    = "span8">
			<h1><%= @dog.name %></h1>
		</div>
		<Div class    = "span4">

		</div>
	</div>
</div>

<div class      = "row">

	<div class     = "span5">
		<a href       = "#" class="thumbnail">
			
			<% if @dog.avatar_file_name == nil && @dog.gender == "Female" %>
				<%= image_tag "/assets/default_dog_large_female.png" %>
			<% else %>
				<%= image_tag @dog.avatar.url(:large) %>
			<% end %>
		</a>

		<p><A href    = "mailto:michael@matchpuppy.com?subject=report profile&body=please take down the dog at <%= user_dog_url(@dog.user, @dog) %>" class="small">Report this profile</a></p>
		</div>

		<div class    = "span7">
			<div class   = "row">
				<div class  = "span4">
					<div class="well">
					<h3>About <%= @dog.name %></h3>
					<ul class  = "unstyled">
						<li><b>Size:</b> <%= @dog.size %></li>

						<li><b>Breed:</b> <%= @dog.breed %></li>

						<li><b>Gender:</b> <%= @dog.gender %></li>
						<li><b>Age:</b> <%= @dog.age %></li>
						
						<li><b>Energy Level:</b> <%= @dog.energy %></li>
						
						<li><b>Owner:</b> <%= link_to @dog.user.name, @dog.user %></li>
					</ul>
					<p>
					
					&ldquo;<%= @dog.favorite %>&rdquo;
							
					</p>
					</div>
					
					<div class="well">
					<h3>Dog parks <% if @dog.gender == "Male" %>he<% else %>she<% end %> loves</h3>
				
					<%= render @dog.park_loves %>
					</div>

				

				</div>
				<div class  = "span3">
					
					<div class="well">
							<h3>Share <%= @dog.name %></h3>

							<div class = "fb-like" data-layout="button_count" data-send="true" data-width="100" data-show-faces="false"></div>
							<br/>
							<a href    = "https://twitter.com/share" class="twitter-share-button" data-via="matchpuppy" data-size="small">Tweet</a>
					</div>
					<div class="well">
					<h3>Upcoming Playdates</h3>
						<%= render @playdates %>
					</div>
					</div>
				</div>
			</div>

			
		</div>

		<div class   = "row" >
			<div class  = "span12">
				<div class="well">
				<h3>Other <%= @dog.breed %>s</h3>
				<ul class  = "thumbnails">
					<%= render @other_dogs %>
				</ul>
				</div>
			</div>
		</div>



	<% if @dog.user == current_user %>

	<div class     = "form-actions">	
		<a href       = "<%= edit_user_dog_path(@user,@dog) %>" class="btn">
			<i class     = "icon-pencil"></i> Edit <%= @dog.name %>
		</a>

		<a href       = "<%= user_dog_path(@user,@dog) %>" data-method="delete" class="btn btn-danger">
			<i class     = "icon-remove"></i> Delete <%= @dog.name %>
		</a>


	</div>
	<% end %>