config/routes.rb
Matchpuppy::Application.routes.draw do
  
  

  
  match 'privacy' => 'pages#privacy'
  match 'terms' => 'pages#terms'
  match 'contact' => 'pages#contact'
  match 'faq' => 'pages#faq'
  
  
  get "pages/terms"

  resources :park_loves
  resources :comments
  

 match 'account' => 'users#profile'
 match 'account/edit' => 'users#edit'
 
  
  resources :user_sessions
  
   resources :password_resets

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  resources :playdates do
    resources :playdate_guests
    resources :comments
  end
  
  match 'playdates/:id/join' => 'playdates#join'
  match 'playdates/:id/rsvp/:rsvp' => 'playdates#rsvp'
  
  
  
  
  resources :parks
  
  resources :posts

 root :to => 'users#new'
 

  
  resources :users do
    resources :dogs
  end
  
  
  resources :contact_us 
  
  match 'contact_us/send_email' => 'contact_us#send_email', :as => :send_email
   
  
  match 'dogs' => 'dogs#index'
  
  match 'admin/:action' => 'admin'
  
end

app/models/city_park.rb
class CityPark < ActiveResource::Base
  self.site = "http://www.nycgovparks.org/bigapps/DPR_DogRuns_001.xml"
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :playdate
  has_one :park, :through => :playdate
  
  after_save :notify
  
  
  private
  
  def notify
    PlaydateMailer.new_comment(self).deliver
  end
  
  
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Validations
  include ActiveModel::Conversion
  
  attr_accessor :name, :email, :body
  validates_presence_of :name, :email, :body
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end 
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :large=> "600",:medium => "300", :thumb => "150" }, :storage => :s3,
      :bucket => 'MatchPuppy',
      :s3_credentials => {
        :access_key_id => 'AKIAJYTNN7664YXLY5KA',
        :secret_access_key => '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'
      }, 
      :default_url => '/assets/default_dog_:style.png'
      
  validates_attachment_size :avatar, :less_than => 5.megabytes
  
  belongs_to :user
  has_many :playdate_guests, :dependent => :destroy
  has_one :park, :through => :user
  has_many :playdates, :through => :playdate_guests
  has_many :park_loves, :through => :user
  
  validates :name, :size, :breed, :gender, :energy, :age, :favorite, :presence => true
  
  self.per_page = 30
  
  
  
end

app/models/love.rb
class Love < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base
  
  has_many :playdates
  has_many :playdate_guests, :through => :playdates
  has_many :park_loves, :dependent => :destroy
  has_many :users, :through => :park_loves
  has_many :dogs, :through => :users
  
  
  
  def current_love
    if UserSession.find
      @park_love = ParkLove.where(:park_id => self.id, :user_id => UserSession.find.user.id)
      if @park_love.any?
        return true
      else
        return false
      end
    else 
      return false
    end
    
  end
  
end

app/models/park_love.rb
class ParkLove < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
  has_many :playdate_guests, :dependent => :destroy
  has_many :dogs, :through => :playdate_guests
  has_many :comments
  has_many :users, :through => :dogs
  
  validates :park_id, :description, :presence => true
  
  after_save :invite_guests
  
  scope :upcoming, where("playdates.play_date > ?", Time.now).order("play_date ASC")
  
  private 
  
  def invite_guests
    if self.status == "sent"
      self.users.each do |user| 
        if user != self.user
          PlaydateMailer.invite(self, user).deliver
        end
      end
      PlaydateMailer.create(self).deliver
    end
    
  end
  
  
  
end

app/models/playdate_guest.rb
class PlaydateGuest < ActiveRecord::Base
  belongs_to :playdate
  belongs_to :dog
  has_one :user, :through => :dog
  has_one :park, :through => :playdate
  
  scope :yes, where(:rsvp => 'Yes')
  scope :no, where(:rsvp => 'No')
  scope :maybe, where(:rsvp => 'Maybe')
  

 
end

app/models/user.rb
class User < ActiveRecord::Base
 
  acts_as_authentic do |c|
      c.merge_validates_format_of_email_field_options :message => 'not valid'
  end
  
  
  has_many :dogs, :dependent => :destroy
  has_many :playdates
  has_many :park_loves
  has_many :comments
  has_many :parks, :through => :park_loves
  
  validates :name, :email, :password, :presence => true

  
  
  after_create :signup_email
  
  
  def deliver_password_reset_instructions!  
    reset_perishable_token!  
    UserMailer.password_reset(self).deliver
  end
  
  private
  
  def signup_email
    UserMailer.signup(self).deliver
  end
  
  
  def mailing_list
    h = Hominid::API.new('eef9cbf1cbad4b743302e591e036190d-us4')
    h.list_subscribe(22865, 'joe@public.com', {'FNAME' => 'Joe', 'LNAME' => 'Public'}, 'html', false, true, true, false)
    
  end
  
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/loves_helper.rb
module LovesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/comments.html.erb
<% if notice %>
<div class="alert alert-info">
<%= notice %>
</div>
<% end %>


<h1>Listing comments</h1>

<div class="well">
<table class="table-striped table table-condensed">
  <tr>
    <th>User</th>
    <th>Playdate at</th>

    <th>Comment</th>
	<th>Posted on</th>

    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= link_to comment.user.name, comment.user %></td>
    <td></td>
    <td><%= comment.body %></td>

	<td><%= l comment.created_at, :format => :long %></td>
	
  
    <td><%= link_to 'Edit', edit_comment_path(comment), :class=>"btn btn-info" %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete , :class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>
</div>

app/views/admin/dogs.html.erb
<% if notice %>
<div class="alert alert-info">
<%= notice %>
</div>
<% end %>

<div class="page-header">
<h1>Admin Dogs</h1>
</div>

<div class="well">
<table class="table-striped table table-condensed">
<thead>  
<tr>
    <th>Name</th>
    <th>Size</th>
	<th>Breed</th>
    <th>Gender</th>
    <th>Energy</th>
	<th></th>
    
  </tr>
</thead>
<tbody>
<% @dogs.each do |dog|%>

<tr>
    <td><%= dog.name %></td>
    <td><%= dog.size %></td>
	<td><%= dog.breed %></td>
    <td><%= dog.gender %></td>
	<td><%= dog.energy %></td>
	<td>
		<%= link_to "Delete", user_dog_path(dog.user, dog), :method=>'delete', :class=>"btn btn-danger"%>
		
		
	</td>
  </tr>
<% end %>
</table>
</div>

app/views/admin/park_loves.html.erb
<% if notice %>
<div class="alert alert-info">
<%= notice %>
</div>
<% end %>

<div class="page-header">

<h1>Park Loves</h1>

</div>

<div class="well">
<table class="table-striped table table-condensed">
<thead>  
<tr>
    <th>Name</th>
    <th>Borough</th>
	<th>Type</th>
    <th></th>
    
  </tr>
</thead>
<tbody>
<% @park_loves.each do |park_love| %>
  <tr>
    <td><%= park_love.park_id %></td>
  
    <td><%= park_love.user_id %></td>

	
	
	<td>
		
		
		<%= link_to "Delete", park_love, :method=>'delete', :confirm => 'Are you sure?', :class=>"btn btn-danger"%>
		
		
	</td>
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/admin/parks.html.erb
<% if notice %>
<div class="alert alert-info">
<%= notice %>
</div>
<% end %>

<div class="page-header">

<h1>Dog parks</h1>

</div>

<div class="well">
<table class="table-striped table table-condensed">
<thead>  
<tr>
    <th>Name</th>
    <th>Borough</th>
	<th>Type</th>
    <th></th>
    
  </tr>
</thead>
<tbody>
<% @parks.each do |park| %>
  <tr>
    <td><%= link_to park.name, park %></td>
    <td><%= park.borough %></td>
	<td><%= park.park_type %></td>
    <td><%= park.park_loves.count %> dogs love this park</td>

	<td><%= link_to "edit", edit_park_path(park), :class=>"btn btn-info"%></td>
	
	<td>
		
		
		<%= link_to "Delete", park, :method=>'delete', :confirm => 'Are you sure?', :class=>"btn btn-danger"%>
		
		
	</td>
  </tr>
<% end %>
</tbody>
</table>
</div>

<div class="form-actions">
<%= link_to "New Park", new_park_path,  :class=>"btn btn-primary"%>
</div>

app/views/admin/users.html.erb
<% if notice %>
<div class="alert alert-info">
<%= notice %>
</div>
<% end %>

<div class="well">

<h1>Listing users</h1>

<table class="table-striped table table-condensed">
  <tr>
    <th>Name</th>
    <th>Email</th>

	<th>Type</th>

    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <td><%= user.email %></td>

	<td><%= user.user_type %></td>
	
  
    <td><%= link_to 'Edit', edit_user_path(user), :class=>"btn btn-info" %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete , :class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>

</div>

<div class="form-actions">

<%= link_to 'New User', new_user_path, :class=> "btn btn-primary" %>
</div>

app/views/index/index.html.erb
<form action="/user/new" method="post">
	
	<div class="clearfix">
	    <label for="name">Your Name</label>
	    <div class="input">
	      <input class="xlarge" id="name" name="name" size="30" type="text">
	    </div>
	</div>
	
	<div class="clearfix">
	    <label for="email">Your Email</label>
	    <div class="input">
	      <input class="xlarge" id="email" name="email" size="30" type="text">
	    </div>
	</div>
	
	<!-- <div class="clearfix">
		    <label for="dog_name">Your Dog's Name</label>
		    <div class="input">
		      <input class="xlarge" id="dog_name" name="dog_name" size="30" type="text">
		    </div>
		</div> -->
	
	
	<div class="actions">
		<input type="submit" name="submit" value="Sign-Up >" class="btn primary">
	</div>
	
	
	<h1>Hello, Rails!</h1>
	<%= link_to "My Blog", users_path %>
	
</form>