config/routes.rb
Matchpuppy::Application.routes.draw do
  
  

  
  match 'privacy' => 'pages#privacy'
  match 'terms' => 'pages#terms'
  match 'contact' => 'pages#contact'
  match 'faq' => 'pages#faq'
  
  
  get "pages/terms"

  resources :park_loves
  resources :comments
  

 match 'account' => 'users#profile'
 match 'account/edit' => 'users#edit'
 
  
  resources :user_sessions
  
   resources :password_resets

  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'
  
  resources :playdates do
    resources :playdate_guests
    resources :comments
  end
  
  match 'playdates/:id/join' => 'playdates#join'
  match 'playdates/:id/rsvp/:rsvp' => 'playdates#rsvp'
  
  
  
  
  resources :parks
  
  resources :posts

 root :to => 'users#new'
 

  
  resources :users do
    resources :dogs
  end
  
  
  resources :contact_us 
  
  match 'contact_us/send_email' => 'contact_us#send_email', :as => :send_email
   
  
  match 'dogs' => 'dogs#index'
  
  match 'admin/:action' => 'admin'
  
end

app/models/playdate.rb
class Playdate < ActiveRecord::Base
  belongs_to :user
  belongs_to :park
  has_many :playdate_guests, :dependent => :destroy
  has_many :dogs, :through => :playdate_guests
  has_many :comments
  has_many :users, :through => :dogs
  
  validates :park_id, :description, :presence => true
  
  after_save :invite_guests
  
  scope :upcoming, where("playdates.play_date > ?", Time.now).order("play_date ASC")
  
  private 
  
  def invite_guests
    if self.status == "sent"
      self.users.each do |user| 
        if user != self.user
          PlaydateMailer.invite(self, user).deliver
        end
      end
      PlaydateMailer.create(self).deliver
    end
    
  end
  
  
  
end

app/controllers/playdates_controller.rb
class PlaydatesController < ApplicationController
  # GET /playdates
  # GET /playdates.json
  before_filter :require_user, :except => :index
  before_filter :set_controller
  
  def index
    @title = "Playdates"
    @playdates = Playdate.upcoming
    
  end

  # GET /playdates/1
  # GET /playdates/1.json
  def show
    @playdate = Playdate.find(params[:id])
    @playdate_guests = @playdate.playdate_guests

    @park = Park.find(@playdate.park_id)
    @guests = Array.new

    @other_playdates = Playdate.where(:park_id => @park.id)
    
    @title = "Playdate for " + l(@playdate.play_date, :format => :playdate)
    
    current_user.dogs.each do |dog|
      @active_guests = @playdate.playdate_guests.where(:dog_id => dog.id)
    end
    
    
    if current_user == @playdate.user
      if @playdate.dogs.empty?
        @dogs = @playdate.park.dogs
      else
        @dogs = @playdate.park.dogs.where("dogs.id not IN (?)", @playdate.dogs )
      end
    
      @dogs.each do |dog| 
        @guests << PlaydateGuest.new(:dog_id => dog.id)
      end
    
    else
      current_user.dogs.each do |dog|
        @guests << PlaydateGuest.new(:dog_id => dog.id)
      end
    end

  end

  # GET /playdates/new
  # GET /playdates/new.json
  def new
    @playdate = Playdate.new
    @playdate.user_id = current_user.id
    @playdate.park_id = current_user.park_id
    @parks = Park.joins(:users).where("users.id" => current_user.id)
    
    @other_playdates = Array.new
    
    @title = "New Playdate"
    
    current_user.parks.each do |park|
      @other_playdates = Playdate.upcoming.where(:park_id => park.id)
    end
    
    
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @playdate }
    end
  end

  # GET /playdates/1/edit
  def edit
    @playdate = Playdate.find(params[:id])
    @parks = Park.all
    
  end

  def join
    @playdate = Playdate.find(params[:id])
    current_user.dogs.each do |dog|
      @playdate.playdate_guests.create(:dog_id => dog.id, :rsvp=>"Yes") 
      
    end
    
    PlaydateMailer.join(@playdate, current_user).deliver
    
    redirect_to @playdate, :notice => "You've successfully joined this playdate"
  end
  
  def rsvp
    @playdate = Playdate.find(params[:id])
    
    current_user.dogs.each do |dog|
      @playdate_guest = @playdate.playdate_guests.where(:dog_id => dog.id)
      @playdate_guest.first.update_attributes(:rsvp=>params[:rsvp])
    end
    
    redirect_to @playdate, :notice => "RSVP Updated"
    
  end

  
  # POST /playdates
  # POST /playdates.json
  def create
    @playdate = Playdate.new(params[:playdate])
    @playdate.user_id = current_user.id
    
    @parks = Park.joins(:users).where("users.id" => current_user.id)
    
    current_user.dogs.each do |dog|
      @playdate.playdate_guests.new(:dog_id => dog.id, :rsvp=>"Yes") 
     
    end
    
    

    respond_to do |format|
      if @playdate.save
        format.html { redirect_to @playdate, :notice => 'Playdate was successfully created. Invite some dogs who love this park.' }
        format.json { render :json => @playdate, :status => :created, :location => @playdate }
      else
        format.html { render :action => "new" }
        format.json { render :json => @playdate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /playdates/1
  # PUT /playdates/1.json
  def update
    @playdate = Playdate.find(params[:id])

    respond_to do |format|
      if @playdate.update_attributes(params[:playdate])
        format.html { redirect_to @playdate, :notice => 'Playdate was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @playdate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playdates/1
  # DELETE /playdates/1.json
  def destroy
    @playdate = Playdate.find(params[:id])
    @playdate.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :ok }
    end
  end
  
  
  private
  
  def set_controller
     @controller = 'playdates'
   end
  
 
  
end

app/helpers/playdates_helper.rb
module PlaydatesHelper
end

app/views/playdates/_form.html.erb
<style>
	#playdate_play_date_2i {
		
		width:100px;
	}
	#playdate_play_date_4i {
		width:75px;
	}
  #playdate_play_date_3i,  #playdate_play_date_5i    {width:50px;}
</style>




<%= form_for(@playdate, :html => {:class=> "form-horizontal"}) do |f| %>
  <% if @playdate.errors.any? %>
  <div class="alert alert-error">
      <strong>Whoops!</strong>

      <ul>
      <% @playdate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="control-group">
	<%= f.label "Which Park?" %>
	<div class="controls">
		<%= f.select(:park_id, @parks.map {|u| [u.name,u.id]}) %>
		<p class="help-block">You can only schedule playdates at parks that you love.  <%= link_to "Find more parks to love >", parks_path %></a></p>
	</div>
</div>

<div class="control-group">
	<%= f.label "When?" %>
	<div class="controls">
		<%= f.datetime_select :play_date, :order => [:month, :day],  :default => 1.days.from_now, :ampm => true,  :minute_step => 15  %>
	</div>
</div>


<!--  <div class="control-group">

	<%= f.label "What Time?" %>
	<div class="controls">
		<%= f.time_select :play_date, :class=>"span2", :ampm => true,  :minute_step => 15 %>
	</div>
</div> -->

<div class="control-group">
	<%= f.label "What's the plan?" %>
	<div class="controls">
		<%= f.text_area :description, :width=>'100%' %>
		<div class="help-block">Eg. Just wanna have fun or let's go running together</div>
	</div>
</div>	






  
  <div class="form-actions">
    <%= f.submit nil, :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/playdates/_playdate.html.erb
<ul class="unstyled">
<li>
<a href="<%= playdate_path(playdate) %>" ><strong><i class="icon-calendar"></i> <%=l playdate.play_date, :format => :playdatetime  %></strong></a></li>
<li><i class="icon-leaf"></i> <%= link_to playdate.park.name, playdate.park %></li> 
<li><p>(<%= pluralize(playdate.playdate_guests.yes.count, 'dog') %> coming)</p></li>
</ul>

 

app/views/playdates/edit.html.erb
<h1>Editing playdate</h1>

<%= render 'form' %>

<%= link_to 'Back', parks_path, :class=>"btn" %>

app/views/playdates/index.html.erb
<div class="page-header">
<h1>Upcoming playdates</h1>
</div>

<div class="row">
	<div class="span8">
<Div class="well">

<table class="table-striped table table-condensed">
<thead>  
<tr>
    <th>Date</th>
    <th>Park</th>
	<th>Dogs Coming</th>
    <th></th>
    
  </tr>
</thead>
<tbody>
	
	<% @playdates.each do |playdate| %>
		<tr>
	    <td><a href="<%= playdate_path(playdate) %>" ><strong><i class="icon-calendar"></i> <%=l playdate.play_date, :format => :playdatetime  %></strong></a></td>
	    <td><i class="icon-leaf"></i> <%= link_to playdate.park.name, playdate.park %></td>
		<td>(<%= pluralize(playdate.playdate_guests.yes.count, 'dog') %> coming)</td>
	    </tr>
	
	
	<% end %>
	
</tbody>
</table>
<div class="form-actions">

<%= link_to 'Schedule a New Playdate', new_playdate_path, :class => "btn btn-primary" %>
</div>
</div>
</div>
</div>

app/views/playdates/new.html.erb
<div class="page-header">
<h1>Schedule a new playdate</h1>
</div>

<div class="row">

<div class="span8">
	<div class="well">
<%= render 'form' %>
	</div>
</div>



</div>

app/views/playdates/show.html.erb
<% content_for :head do %>
  	<meta property="og:image" content="http://www.matchpuppy.com/assets/logo_beta.png"/>
	<meta property="og:url" content="<%= playdate_url(@playdate) %>"/>
	<link rel="canonical" href="<%=  playdate_url(@playdate) %>" />
<% end %>


<% if notice %>
<div class="alert alert-success">
<%= notice %>
</div>
<% end %>

<div class="page-header">
	<div class="row">
		<div class="span8">
			<h1>
				<% if @playdate.user == current_user %>Your <% end %>playdate for <%= l @playdate.play_date, :format => :playdate %>
			</h1>
		</div>

	</div>
</div>

<div class="row">

	<div class="span2" style=" ">
		<h3>Instigator</h3>

		<a href="<%= user_dog_path(@playdate.user, @playdate.user.dogs.last) %>"><%= image_tag @playdate.user.dogs.first.avatar.url(:medium) %></a>
		<h4><%= link_to @playdate.user.dogs.first.name, user_dog_path(@playdate.user, @playdate.user.dogs.last) %> </h4>
		<ul class="unstyled">
			<li>Breed: <%= @playdate.user.dogs.first.breed %> </li>
			<li>Gender: <%= @playdate.user.dogs.first.gender%> </li>
			<li>Owner: <%= link_to @playdate.user.name, @playdate.user %> </li>

		</ul>
		<% if @playdate.user == current_user %>
		<!-- <%= link_to "Edit Playdate", edit_playdate_path(@playdate)%> -->
	
		<% end %>
	</ul>


</div>



<div class="span7">
	<!-- if havent finalized playdate yet -->
	<% if !@playdate.status && @playdate.user == current_user %>
	<div class="well">
		<h3>Invite dogs who love this park</h3>
		<p>Select the dogs you want to invite from the list below.  When your finished click to finalize playdate to email and invite guests.</p>

		<% if @guests.count > 0 %>
			<ul class="thumbnails">
				<% @guests.each do |playdate_guest| %>
					<li id="invitee<%= playdate_guest.dog.id %>" >
						<div class="thumbnail">
							<a href="#" rel="popover" data-placement="right" data-delayHide="5000" data-original-title="<%= playdate_guest.dog.name %>" data-content="
								<ul class='unstyled''>
							    <li><b>Size:</b> <%= playdate_guest.dog.size %></li>
								<li><b>Breed:</b> <%= playdate_guest.dog.breed %></li>
								<li><b>Gender:</b> <%= playdate_guest.dog.gender %></li>
								<li><b>Age:</b> <%= playdate_guest.dog.age %></li>
								
								<li><b>Energy:</b> <%= playdate_guest.dog.energy %></li>
								
								<li>&ldquo;<%= playdate_guest.dog.favorite %>&rdquo;</li>
							  </ul>
								" data-html="true">
							
							
							 <% if playdate_guest.dog.avatar_file_name == nil && playdate_guest.dog.gender == "Female" %>
								<%= image_tag "/assets/default_dog_thumb_female.png" %>
							<% else %>
								<%= image_tag playdate_guest.dog.avatar.url(:large) %>
							<% end %>
							</a>


							<%= form_for([@playdate,playdate_guest], :remote => true, :html=>{:class=>"invite"}) do |f| %>
								<%= f.hidden_field :dog_id  %>
								<%= f.submit "Invite "+playdate_guest.dog.name, :class=>"btn btn-info" %>
							<% end %>
						</div>
					</li>
				<% end %>
			</ul>
			
			
		
		<% else %>
			<div class="help-block">
					<p>No other dogs love this park right now, but you can schedule the playdate and others can sign up and join later.</p>
				<p>  Help spread the word about matchpuppy, share it on facebook and twitter</p>
			</div>
		<% end %>
		
		
</div>
		<div class="form-actions">

			<%= form_for(@playdate) do |f| %>
			<%= f.hidden_field :status  %>
			<%= f.submit "Finalize Playdate and Invite Guests", :class=>"btn btn-primary" %>

			<% end %>

		</div>
	
	<!-- if have finalized playdate  -->	
	<% else %>

		<div class="well">
			<ul class="unstyled">
				<li>
					<i class="icon-calendar"></i> <b>Starts at:</b> <%= l @playdate.play_date, :format => :playdatetime %>	
				</li>
				<li><i class="icon-leaf"></i> <%= link_to @playdate.park.name, @playdate.park %></li>

			</ul>
			<p>
				<%= @playdate.description %>	
			</p>

			<%= render @playdate.park %>
		</div>


		<div class="well">
	
			<h4>Comments</h4>
			<hr/>
				<div >
			<% if @playdate.comments.size > 0 %>
		
				<%= render @playdate.comments %>
		
			<% else %>
				<div class="help-block">No comments yet, use this space to discuss meeting place and plans for the playdate </div>
			<% end %>
				</div>
			<hr/>
			<%= form_for([@playdate, @playdate.comments.build]) do |f| %>
				<%= f.label "Your Comment" %>
				<%= f.text_area :body  %>
		
				<div class="actions">
					<%= f.submit "Comment", :class=>"btn primary" %>
				</div>
			<% end %>
		</div>
	<% end %>

	</div><!-- end middle column -->
	<div class="span3">

		<!-- User Actions -->

		<% if @playdate.user != current_user && @active_guests.length > 0  %>
			<div class="well">
				<h3>Your RSVP?</h3>

				<div class="btn-group">
					<a class="btn btn-info btn-large <% if @active_guests.first.rsvp =="Yes" %>active<% end %>" href="/playdates/<%= @playdate.id %>/rsvp/Yes">Yes</a>
					<a class="btn btn-info btn-large <% if @active_guests.first.rsvp =="Maybe" %>active<% end %>" href="/playdates/<%= @playdate.id %>/rsvp/Maybe">Maybe</a>
					<a class="btn btn-info btn-large <% if @active_guests.first.rsvp =="No" %>active<% end %>" href="/playdates/<%= @playdate.id %>/rsvp/No">No</a>
				</div>
			</div>
		<% elsif @playdate.user != current_user %>
			<div class="well">
				<a href="/playdates/<%= @playdate.id %>/join" class="btn primary large">Join this playdate</a>
				<br/>
			</div>
		<% end %>


		<% if @playdate.status %>
		<div class="well">
			<h3>RSVPs</h3>
			<ul class="unstyled">
				<li>
					<b><i class="icon-ok"></i> Yes:</b>
					<%= @playdate.playdate_guests.yes.count %>	
				</li>
				<li>
					<b>Maybe:</b>
					<%= @playdate.playdate_guests.maybe.count %>	
				</li>

				<li>
					<b><i class="icon-remove"></i> No:</b>
					<%= @playdate.playdate_guests.no.count %>	
				</li>
			</ul>
		</div>
		


		<div class="well">
			<h3>Share this Playdate</h3>
				<div class = "fb-like" data-layout="button_count" data-send="true" data-width="100" data-show-faces="false"></div>
				<br/>
				<a href    = "https://twitter.com/share" class="twitter-share-button" data-via="matchpuppy" data-size="small">Tweet</a>
</div>

<% end %>

<div class="well">
	<h3>Players</h3>
	<ul id="invited" class="thumbnails">
		<%= render @playdate.playdate_guests %>
	</ul>
</div>

</div>

</div>